source 'https://rubygems.org'

Deprecate.skip = true if defined?(Deprecate.skip)
Gem::Deprecate.skip = true if defined?(Gem::Deprecate.skip)

gem 'sqlite3'
gem 'test-unit', '=1.2.3', :platforms => :ruby_19
gem 'hoe', '=2.8.0', :platforms => :ruby_19
gem 'rails', '~>2.3.10'
gem 'rspec', '<2'
gem 'rspec-rails', '<2'
gem 'ruby-debug', :platforms => :ruby_18
gem 'rspec_candy'
gem 'assignable_values', :path => '../..'
