source 'https://rubygems.org'

gem 'sqlite3'
gem 'rails', '4.1.0'
gem 'minitest' # fix MiniTest deprecation warnings
gem 'rspec'
gem 'rspec-rails'
gem 'rspec_candy'
gem 'rspec-collection_matchers' # support for ...should have(n).errors_on ...

gem 'assignable_values', :path => '../..'

group :development do
  gem 'debugger', platform: 'ruby_19'
  gem 'ruby-debug', :platforms => :ruby_18
end
