source 'http://rubygems.org'

gem 'sqlite3'
gem 'rails', '~>3.0.3'
gem 'rspec'
gem 'rspec-rails'
gem 'ruby-debug', :platforms => :ruby_18
gem 'debugger', :platforms => :ruby_19
gem 'rspec_candy'
gem 'assignable_values', :path => '../..'

